import os
import sys
import numpy as np
import mlx.core as mx

# Add project root to path
sys.path.append(os.getcwd())

from piu_annotate.ml.models import MLXModel
from piu_annotate.formats.chart import ChartStruct

def test_inference():
    # Use the specific file generated by training
    model_file = "artifacts/models/visss-mlx/singles-arrows_to_limb-mlx-best.safetensors"
    
    if not os.path.exists(model_file):
        print(f"Error: Model file not found at {model_file}")
        return

    print(f"Loading model from {model_file}...")
    model = MLXModel.load(model_file, input_dim=18)
    
    # Create a dummy sequence of 10 points
    # Each point has 18 features for singles
    dummy_points = np.random.randn(10, 18).astype(np.float32)
    
    print("Testing predict_prob...")
    probs = model.predict_prob(dummy_points)
    print(f"Probs shape: {probs.shape}")
    print(f"Probs sample:\n{probs[:3]}")
    print(f"Probs sum (should be 1 per row):\n{np.sum(probs, axis=1)}")
    
    # Test a longer sequence to trigger sliding window
    print("\nTesting long sequence (600 points)...")
    long_points = np.random.randn(600, 18).astype(np.float32)
    long_probs = model.predict_prob(long_points)
    print(f"Long probs shape: {long_probs.shape}")
    print(f"Long probs sample:\n{long_probs[:3]}")
    print(f"Long probs sum sum (should be approx 1 per row):\n{np.sum(long_probs[:10], axis=1)}")
    
    # Test argmax
    preds = model.predict(long_points)
    print(f"Preds shape: {preds.shape}")
    print(f"Preds sample: {preds[:10]}")

if __name__ == "__main__":
    test_inference()
